# Swedish translations, source indices 0-249
T = {
"+ the domain": "+ domänen",
", and how we handle your information is in the": ", och hur vi hanterar dina uppgifter står i",
", and the wider agreement is in the": ", och det bredare avtalet finns i",
", it covers up to": ", den täcker upp till",
", it stays yours. You remain the registrant and the owner, we simply point it at your website, and nothing about that changes if you leave.": ", förblir den din. Du är fortfarande registrerad innehavare, vi pekar den bara mot din webbplats, och inget med det förändras om du lämnar.",
", one-time)": ", engångsbelopp)",
", or email us. Both work; neither requires a phone call or a reason.": ", eller mejla oss. Båda fungerar; inget av dem kräver telefonsamtal eller en anledning.",
", paid once.": ", betalas en gång.",
", so a typo cannot lock you out again.": ", så ett stavfel inte kan låsa ut dig igen.",
", where we do not have to keep it for legal or accounting reasons.": ", där vi inte behöver spara den av juridiska eller bokföringsmässiga skäl.",
", which works the same way from your point of view: data kept in your browser, on your device, that we can read when you come back.": ", som fungerar på samma sätt ur ditt perspektiv: data som sparas i din webbläsare, på din enhet, och som vi kan läsa när du kommer tillbaka.",
". A person answers.": ". En människa svarar.",
". A reasonable change is a small content update, for example:": ". En skälig ändring är en mindre innehållsuppdatering, till exempel:",
". It includes up to 15 reasonable changes a month, requested from your dashboard.": ". Den inkluderar upp till 15 skäliga ändringar per månad, beställda från din panel.",
". Nothing is pre-selected, refusing takes exactly one click, and refusing does not limit anything on this site.": ". Inget är förvalt, att tacka nej tar exakt ett klick, och ett nej begränsar inget på den här webbplatsen.",
". Pay 25% to start.": ". Betala 25 % för att starta.",
". The": ". Den",
". The final price depends on the length and complexity of the video, and we confirm the figure with you in writing before anything is charged.": ". Slutpriset beror på videons längd och komplexitet, och vi bekräftar beloppet skriftligt med dig innan något debiteras.",
". The final price depends on the number and complexity of the images. These are AI-assisted images, not photographs of your actual products, unless you supply source material we can work from.": ". Slutpriset beror på antalet bilder och hur komplicerade de är. Det här är AI-stödda bilder, inte fotografier av dina faktiska produkter, såvida du inte tillhandahåller underlag som vi kan arbeta från.",
"/ Client dashboard": "/ Kundpanel",
"/ mo": "/ mån",
"/ month": "/ månad",
"/ month)": "/ månad)",
"/ month, after the one-time": "/ månad, efter engångsbeloppet",
"/ month, once the included years run out": "/ månad, när de inkluderade åren tar slut",
"/mo": "/mån",
"01 — Overview & service scope": "01 — Översikt och tjänstens omfattning",
"01 — Who we are": "01 — Vilka vi är",
"02 — Website features & scope": "02 — Webbplatsens funktioner och omfattning",
"02 — What we collect": "02 — Vad vi samlar in",
"03 — Website maintenance": "03 — Webbplatsskötsel",
"03 — Why, and on what legal basis": "03 — Varför, och på vilken rättslig grund",
"04 — Marketing email": "04 — Reklammejl",
"04 — Payment": "04 — Betalning",
"05 — Delivery": "05 — Leverans",
"05 — How long we keep it": "05 — Hur länge vi sparar den",
"06 — Monthly billing": "06 — Månadsfakturering",
"06 — Who else processes it": "06 — Vem annars behandlar den",
"07 — Failed payments": "07 — Misslyckade betalningar",
"07 — Transfers outside the EEA": "07 — Överföringar utanför EES",
"08 — Cancellation & refunds": "08 — Uppsägning och återbetalningar",
"08 — Your rights": "08 — Dina rättigheter",
"09 — Domain ownership": "09 — Domänägarskap",
"09 — Security": "09 — Säkerhet",
"10 — Children": "10 — Barn",
"10 — Website code & offboarding": "10 — Webbplatskod och utflyttning",
"11 — Changes": "11 — Ändringar",
"11 — Customer responsibilities": "11 — Kundens ansvar",
"12 — Intellectual property": "12 — Immaterialrätt",
"13 — Hosting & uptime": "13 — Drift och upptid",
"14 — Liability": "14 — Ansvar",
"15 reasonable website changes per month": "15 skäliga webbplatsändringar per månad",
"15 — Changes to these terms": "15 — Ändringar av villkoren",
"16 — Governing law": "16 — Tillämplig lag",
"180 days": "180 dagar",
"25% deposit": "25 % i handpenning",
"25% of your one-time website total. That is the deposit, and it is the only thing charged on the day you order. On a": "25 % av din webbplats engångssumma. Det är handpenningen, och det enda som debiteras dagen du beställer. Vid en",
"34 sections and features, in every website": "34 sektioner och funktioner, i varje webbplats",
"99.9% monthly uptime target": "99,9 % månatligt upptidsmål",
"A cookie is a small piece of text your browser stores for a site. We also use": "En cookie är en liten textbit som din webbläsare sparar för en webbplats. Vi använder också",
"A few sentences about the business, how long you have been going, the areas you cover. Rough notes are fine — we do the writing.": "Några meningar om verksamheten, hur länge ni funnits och vilka områden ni täcker. Kortfattade anteckningar räcker — vi skriver färdigt.",
"A peregrine falcon in a high-speed dive, feathers rippling, eye locked forward": "En pilgrimsfalk i en snabb dykning, fjädrarna fladdrar, blicken låst framåt",
"A project": "Ett projekt",
"A quarter of the one-time total, and that books the work in. Nothing else is charged today.": "En fjärdedel av engångssumman, och därmed bokas jobbet in. Inget annat debiteras idag.",
"A quarter of the one-time total. That is it for now. The rest is due once the site is built and you have said you are happy with it, and nothing monthly gets charged until you are actually live. The order summary spells out all three numbers before you pay anything.": "En fjärdedel av engångssumman. Det är allt för nu. Resten förfaller när webbplatsen är byggd och du har sagt dig nöjd, och inga månadsbelopp dras förrän du faktiskt är live. Ordersammanställningen redovisar alla tre siffrorna innan du betalar något.",
"A short list, honestly described.": "En kort lista, ärligt beskriven.",
"AI Business Photos": "AI-företagsbilder",
"AI Receptionist": "AI-receptionist",
"About Us section": "\"Om oss\"-sektion",
"About a week from the day we have everything — logo, photos, your services and prices, opening hours, how people reach you. It is a target, not a promise carved in stone: if the photos land three weeks later, so does the website.": "Cirka en vecka från den dag vi har allt — logotyp, bilder, era tjänster och priser, öppettider, hur folk når er. Det är ett mål, inte ett stenristat löfte: kommer bilderna tre veckor senare, gör webbplatsen det också.",
"Accept all cookies": "Acceptera alla cookies",
"Accessibility improvements": "Förbättrad tillgänglighet",
"Account": "Konto",
"Account Settings": "Kontoinställningar",
"Account Settings → Notification preferences": "Kontoinställningar → Aviseringsinställningar",
"Account and project information": "Konto- och projektuppgifter",
"Account details": "Kontouppgifter",
"Account, data & support": "Konto, data och support",
"Account, project and payment emails": "Konto-, projekt- och betalningsmejl",
"Add a short description so we know what to change.": "Lägg till en kort beskrivning så vi vet vad som ska ändras.",
"Add-ons only. Your website price is on top, and monthly services start the day you go live.": "Endast tillägg. Webbplatsens pris läggs på toppen, och månadstjänsterna startar den dag du går live.",
"Admin (demo)": "Admin (demo)",
"After the build has started": "Efter att bygget har startat",
"After the website is finished and you have reviewed and approved it. Not before. We do not take it automatically while you are still looking at the site — approving is the action that makes it due.": "Efter att webbplatsen är klar och du har granskat och godkänt den. Inte tidigare. Vi drar den inte automatiskt medan du fortfarande tittar på sajten — godkännandet är det som gör att resten förfaller.",
"All 34 — no limit of twenty.": "Alla 34 — ingen gräns på tjugo.",
"All done": "Allt klart",
"All of this is subject to your statutory rights, which we cannot and do not sign away — see clause 05.": "Allt detta är underkastat dina lagstadgade rättigheter, vilka vi varken kan eller frånsäger oss — se klausul 05.",
"All paid once. The domain, the hosting and the padlock come with every one of them.": "Allt betalas en gång. Domänen, driften och hänglåset följer med vart och ett av dem.",
"Almost always a trailing space from a paste, or Caps Lock on for one field and off for the other. Clear both boxes and type it twice by hand.": "Nästan alltid ett mellanslag på slutet från en inklistring, eller Caps Lock påslaget i ett fält men inte i det andra. Rensa båda fälten och skriv manuellt två gånger.",
"Already a customer?": "Redan kund?",
"Already have an account?": "Har du redan ett konto?",
"Already own one? Put it here. If not, tell us the name you would like and we will check what is free.": "Äger du redan en? Skriv den här. Om inte, ange namnet du vill ha så kollar vi vad som är ledigt.",
"Analytics": "Analys",
"Analytics and conversion tracking.": "Analys och konverteringsmätning.",
"Announcements section": "Meddelandesektion",
"Answer support messages": "Svara på supportmeddelanden",
"Any 20 of the 34, your pick.": "Valfria 20 av de 34, du väljer.",
"Any other feature or service is included": "Ingen annan funktion eller tjänst ingår",
"Any text you want on the page": "Valfri text du vill ha på sidan",
"Anything still missing pushes the delivery date out by however long it takes to arrive. Nothing else changes — your price stays exactly what you agreed at checkout.": "Det som fortfarande saknas skjuter leveransdatumet framåt med den tid det tar att komma fram. Inget annat förändras — ditt pris blir exakt det du accepterade i kassan.",
"Anything you want written on the page": "Vad du än vill ska stå på sidan",
"Appointment calendar": "Bokningskalender",
"Appointment reminder emails": "Påminnelsemejl för bokningar",
"Approve it, pay the rest": "Godkänn den, betala resten",
"Approximately 7 days after we receive everything needed to build it. That is a target we work to, not an unconditional guarantee — and the clock starts when the last piece of content arrives, not when you pay.": "Ungefär 7 dagar efter att vi fått allt som behövs för att bygga den. Det är en målsättning vi arbetar efter, inte ett ovillkorligt löfte — och klockan startar när sista innehållet kommit in, inte när du betalar.",
"Are Business Extras monthly payments?": "Är Business Extras månadsbetalningar?",
"Are Business Extras required?": "Krävs Business Extras?",
"Are there any other costs?": "Finns det några andra kostnader?",
"Are these monthly payments?": "Är det här månadsbetalningar?",
"Ask before you buy. We would rather answer a question now than have you order the wrong thing.": "Fråga innan du köper. Vi svarar hellre på en fråga nu än att du beställer fel.",
"Ask us instead": "Fråga oss istället",
"At checkout we ask you to confirm the payment schedule before you pay, and we record that confirmation. If the applicable rules require a specific early-commencement acknowledgement, it belongs at that same point in the flow — it is marked in the checkout for the same review.": "I kassan ber vi dig bekräfta betalningsplanen innan du betalar, och vi sparar den bekräftelsen. Om gällande regler kräver en särskild bekräftelse om tidig verkställighet hör den hemma på samma steg i flödet — den är markerad i kassan för samma granskning.",
"Automated customer responses": "Automatiserade kundsvar",
"Automatic email notifications": "Automatiska mejlaviseringar",
"Back": "Tillbaka",
"Back to log in": "Tillbaka till inloggningen",
"Back to pricing": "Tillbaka till priserna",
"Back-to-top button": "Knapp till toppen",
"Bakery": "Bageri",
"Barbershop": "Barbershop",
"Basic SEO setup": "Grundläggande SEO-uppsättning",
"Basic SEO, Google indexing and Search Console.": "Grundläggande SEO, Google-indexering och Search Console.",
"Because you have never met us. Handing a stranger hundreds of euro for a website that does not exist yet is a bad deal, and we would rather not ask for it.": "För att ni aldrig har träffat oss. Att lämna över hundratals euro till en främling för en webbplats som ännu inte finns är en dålig affär, och vi vill helst inte be om det.",
"Before & after section": "\"Före/efter\"-sektion",
"Before we have started building": "Innan vi har börjat bygga",
"Before you write": "Innan du skriver",
"Billing starts when your website goes live and continues each month until you cancel, under the cancellation terms below.": "Faktureringen startar när din webbplats går live och fortsätter varje månad tills du säger upp den, enligt uppsägningsvillkoren nedan.",
"Blog section": "Bloggsektion",
"Booking confirmation emails": "Mejl med bokningsbekräftelser",
"Booking, SEO, analytics, automation, a logo, an email on your own domain. Sixty-six one-off jobs and ten monthly services, each priced on its own page so you can tick your way to a total before you talk to anyone.": "Bokning, SEO, analys, automation, en logotyp, en mejladress på egen domän. Sextiosex engångsjobb och tio månadstjänster, vart och ett prissatt på egen sida så att du kan bocka dig fram till en totalsumma innan du pratar med någon.",
"Booking, SEO, analytics, automation, a logo, an email on your own domain. Sixty-six one-off jobs.": "Bokning, SEO, analys, automation, en logotyp, en mejladress på egen domän. Sextiosex engångsjobb.",
"Brand": "Varumärke",
"Brand & design": "Varumärke och design",
"Brand Kit": "Varumärkeskit",
"Broken-link checking": "Kontroll av trasiga länkar",
"Build and host your website": "Bygg och drifta din webbplats",
"Build my website": "Bygg min webbplats",
"Build my website —": "Bygg min webbplats —",
"Build updates, review requests, payment reminders, failures": "Bygguppdateringar, omdömesförfrågningar, betalningspåminnelser, felmeddelanden",
"Build your package": "Bygg ditt paket",
"Built around what you actually do, and made to work on a phone — because that is where people find you. Domain, hosting and padlock included.": "Byggd kring det du faktiskt gör, och gjord för att fungera på mobilen — för där hittar folk dig. Domän, drift och hänglås ingår.",
"Business & technical": "Affärs- och tekniskt",
"Business Card Design": "Design av visitkort",
"Business Document Templates": "Dokumentmallar för företag",
"Business Extras": "Business Extras",
"Business Information": "Företagsinformation",
"Business address": "Företagsadress",
"Business email set up.": "Företagsmejl konfigurerat.",
"Business information": "Företagsinformation",
"Business inquiry form": "Formulär för företagsförfrågningar",
"Business name": "Företagsnamn",
"Businesses we build for": "Företag vi bygger för",
"Butcher": "Slaktare",
"Buying a website does not sign you up to a mailing list. Marketing email is a separate, unticked choice at checkout and in your account settings, and saying no has no effect on what you buy or how we support you.": "Att köpa en webbplats gör dig inte medlem i en utskickslista. Reklammejl är ett separat, obokat val i kassan och i kontoinställningarna, och att säga nej påverkar inte vad du köper eller hur vi hjälper dig.",
"Café": "Café",
"Can I add extras after ordering my website?": "Kan jag lägga till tillägg efter att jag beställt min webbplats?",
"Can I add or stop a monthly service later?": "Kan jag lägga till eller avsluta en månadstjänst senare?",
"Can I cancel a monthly service?": "Kan jag säga upp en månadstjänst?",
"Can I order just a logo without a website?": "Kan jag beställa bara en logotyp utan webbplats?",
"Can I remove an extra before paying?": "Kan jag ta bort ett tillägg innan jag betalar?",
"Can I request changes after launch?": "Kan jag beställa ändringar efter lanseringen?",
"Can I see the website before paying the final 75%?": "Kan jag se webbplatsen innan jag betalar slutliga 75 %?",
"Can I take my website somewhere else?": "Kan jag ta min webbplats någon annanstans?",
"Cancellation & Refund Policy": "Policy för uppsägning och återbetalning",
"Cancellation & refunds": "Uppsägning och återbetalningar",
"Cancelling is explained in the": "Uppsägning förklaras i",
"Car wash": "Biltvätt",
"Card details, payment status, subscriptions, refunds": "Kortuppgifter, betalningsstatus, prenumerationer, återbetalningar",
"Card numbers, expiry dates and security codes go directly to the payment provider. We receive a reference, an amount and a status — never the card itself.": "Kortnummer, utgångsdatum och säkerhetskoder går direkt till betalleverantören. Vi får en referens, ett belopp och en status — aldrig kortet självt.",
"Careers section": "Jobbsektion",
"Catalogues & documents": "Kataloger och dokument",
"Change my cookie choice": "Ändra mitt cookie-val",
"Changes": "Ändringar",
"Changes & maintenance": "Ändringar och underhåll",
"Changes made by Google, Meta or other third-party platforms": "Ändringar gjorda av Google, Meta eller andra tredjepartsplattformar",
"Changes to these terms": "Ändringar av dessa villkor",
"Changing text on the page": "Ändra text på sidan",
"Check your code": "Kolla din kod",
"Check your inbox": "Kolla inkorgen",
"Children": "Barn",
"Choose a new password": "Välj ett nytt lösenord",
"Choose a website to begin": "Välj en webbplats för att börja",
"Clear": "Rensa",
"Close menu": "Stäng menyn",
"Codes also expire on their own after ten minutes. A code you found half an hour later will be refused even though it looks right.": "Koder upphör också att gälla av sig själva efter tio minuter. En kod du hittar en halvtimme senare avslås även om den ser rätt ut.",
"Coming soon": "Kommer snart",
"Compare the two": "Jämför de två",
"Complete Package is the Full Website plus the work around it: maintenance, Local SEO, a logo and menu design, WhatsApp Business and business email, and three years of hosting instead of one. All three are paid one time.": "Complete Package är Full Website plus arbetet runtom: skötsel, lokal SEO, logotyp- och menydesign, WhatsApp Business och företagsmejl, samt tre års drift istället för ett. Alla tre betalas en gång.",
"Confirm": "Bekräfta",
"Confirm new password": "Bekräfta nytt lösenord",
"Confirm password": "Bekräfta lösenord",
"Confirm your email": "Bekräfta din e-postadress",
"Consent": "Samtycke",
"Contact": "Kontakt",
"Contact details for the provider are on the": "Kontaktuppgifter till leverantören finns på",
"Contact form email notifications": "Mejlaviseringar från kontaktformuläret",
"Contact form spam protection": "Skräppostskydd för kontaktformuläret",
"Contact information": "Kontaktinformation",
"Contact us": "Kontakta oss",
"Content you provide": "Innehåll du tillhandahåller",
"Content you provided": "Innehåll du tillhandahöll",
"Contents": "Innehåll",
"Continue": "Fortsätt",
"Conversion tracking": "Konverteringsmätning",
"Cookie": "Cookie",
"Cookie Policy": "Cookiepolicy",
"Cookie banner, privacy and terms pages.": "Cookiebanner samt sidor för integritetspolicy och villkor.",
"Cookie consent banner": "Cookie-samtyckesbanner",
"Cookie settings": "Cookie-inställningar",
"Cookies": "Cookies",
"Correct it": "Rätta det",
"Countries": "Länder",
"Country dialling code": "Landsnummer",
"Create an account": "Skapa ett konto",
"Create an account to build your package": "Skapa ett konto för att bygga ditt paket",
"Create and run your account": "Skapa och förvalta ditt konto",
"Create one": "Skapa ett",
"Custom 404 page": "Egen 404-sida",
"Custom Website (": "Skräddarsydd webbplats (",
"Custom Website builds any twenty of the 34, your choice, with three as the minimum. The": "Custom Website bygger valfria tjugo av de 34, du väljer, med tre som minimum. Den",
}
