# -*- coding: utf-8 -*-
# Turkish translations for indices 0-199
L = [
'+ alan adı',
', ve bilgilerinizi nasıl işlediğimiz',
', ve daha kapsamlı sözleşme ise şurada:',
', şu tutara kadar kapsar:',
', o da sizin kalır. Kayıt sahibi ve sahip sizsiniz; biz yalnızca onu web sitenize yönlendiriyoruz ve siz ayrılsanız bile bunda hiçbir değişiklik olmaz.',
', tek seferlik)',
', ya da bize e-posta gönderin. İkisi de işe yarar; ikisi de telefon görüşmesi veya gerekçe gerektirmez.',
', tek seferlik ödenir.',
', böylece bir yazım hatası sizi tekrar dışarıda bırakamaz.',
', yasal veya muhasebe nedenleriyle saklamak zorunda olmadığımız durumlar dışında.',
', tarayıcınızda, cihazınızda tuttuğumuz ve geri geldiğinizde okuyabildiğimiz veri anlamına gelir; açısından tamamen aynı şekilde çalışır.',
'. Yanıtı bir insan verir.',
'. Makul değişiklik, örneğin küçük bir içerik güncellemesidir:',
'. Ayda 15 makul değişiklik dahildir; talepler panonuzdan iletilir.',
'. Hiçbir şey önceden seçili değildir, reddetmek tam olarak tek tıklama sürer ve reddetmek sitede hiçbir şeyi kısıtlamaz.',
'. Başlamak için %25 ödeyin.',
'. ',
". Videonun uzunluğuna ve karmaşıklığına bağlıdır ve herhangi bir ücret alınmadan önce tutarı sizinle yazılı olarak teyit ederiz.",
'. Görsellerin sayısına ve karmaşıklığına bağlıdır. Bunlar, üzerinde çalışabileceğimiz kaynak malzeme göndermedikçe gerçek ürünlerinizin fotoğrafları değil, yapay zekâ destekli görsellerdir.',
'/ Müşteri paneli',
'/ ay',
'/ ay',
'/ ay)',
'/ ay, tek seferlik ödemeden sonra',
'/ ay, dahil olan yıllar dolduğunda',
'/ay',
'01 — Genel bakış ve hizmet kapsamı',
'01 — Biz kimiz',
'02 — Web sitesi özellikleri ve kapsam',
'02 — Neleri topluyoruz',
'03 — Web sitesi bakımı',
'03 — Neden ve hangi hukuki dayanakla',
'04 — Pazarlama e-postası',
'04 — Ödeme',
'05 — Teslimat',
'05 — Ne kadar süre saklıyoruz',
'06 — Aylık faturalandırma',
'06 — Başka kimler işliyor',
'07 — Başarısız ödemeler',
'07 — AEA dışına aktarımlar',
'08 — İptal ve iadeler',
'08 — Haklarınız',
'09 — Alan adı mülkiyeti',
'09 — Güvenlik',
'10 — Çocuklar',
'10 — Web sitesi kodu ve ayrılma',
'11 — Değişiklikler',
'11 — Müşteri sorumlulukları',
'12 — Fikri mülkiyet',
'13 — Barındırma ve çalışma süresi',
'14 — Sorumluluk',
'ayda 15 makul web sitesi değişikliği',
'15 — Bu koşullarda yapılan değişiklikler',
'16 — Uygulanacak hukuk',
'180 gün',
'%25 ön ödeme',
'Tek seferlik web sitesi toplamınızın %25’i. Bu, ön ödemedir ve sipariş verdiğiniz gün alınan tek ücrettir. Bir',
'Her web sitesinde 34 bölüm ve özellik',
'Aylık %99,9 çalışma süresi hedefi',
'Çerez, tarayıcınızın bir site için sakladığı küçük bir metindir. Ek olarak şu teknolojiyi de kullanıyoruz:',
'İşletme hakkında birkaç cümle, ne zamandır devam ettiğiniz, hizmet verdiğiniz bölgeler. Taslak notlar yeterlidir — yazmayı biz üstleniriz.',
'Hızlı dalış yapan bir doğan (peregrine falcon), dalgalanan tüyler, ileriye kilitlenmiş bakış',
'Bir proje',
'Tek seferlik toplamın dörtte biri ve iş bu şekilde rezerve edilir. Bugün başka hiçbir ücret alınmaz.',
'Tek seferlik toplamın dörtte biri. Şimdilik bu kadar. Gerisi, site inşa edildiğinde ve memnun kaldığınızı söylediğinizde tahakkuk eder; site gerçekten yayına girene kadar aylık hiçbir ücret alınmaz. Sipariş özeti, herhangi bir ödeme yapmadan önce üç rakamın tümünü açıkça gösterir.',
'Kısa bir liste, dürüstçe anlatılmış hâli.',
'AI İşletme Fotoğrafları',
'AI Resepsiyonist',
'Hakkımızda bölümü',
'Malzemenin tamamına sahip olduğumuz günden itibaren yaklaşık bir hafta — logo, fotoğraflar, hizmetleriniz ve fiyatlarınız, çalışma saatleri, size nasıl ulaşılacağı. Bu bir hedeftir, taşa yazılmış bir söz değildir: fotoğraflar üç hafta sonra ulaşırsa web sitesi de o zaman teslim edilir.',
'Tüm çerezleri kabul et',
'Erişilebilirlik iyileştirmeleri',
'Hesap',
'Hesap Ayarları',
'Hesap Ayarları → Bildirim tercihleri',
'Hesap ve proje bilgileri',
'Hesap ayrıntıları',
'Hesap, veri ve destek',
'Hesap, proje ve ödeme e-postaları',
'Neyi değiştirmemiz gerektiğini bilelim diye kısa bir açıklama ekleyin.',
'Yalnızca eklentiler. Web sitesi fiyatınız ayrıca eklenir ve aylık hizmetler siteniz yayına girdiği gün başlar.',
'Yönetici (demo)',
'Yapım başlatıldıktan sonra',
"Web sitesi tamamlandıktan ve siz inceleyip onayladıktan sonra. Daha önce değil. Siteye hâlâ bakarken otomatik olarak alınmaz — onaylamak, ücretin vadesini gelen eylemdir.",
'Hepsi 34 — yirmilik sınır yok.',
'Her şey tamam',
'Bunların tümü, yasal haklarınızın tabi olduğudur; bunları imzalayamaz ve devretmeyiz — bkz. 5. madde.',
'Hepsi tek seferlik ödeme. Alan adı, barındırma ve güvenlik kilidi her birine dahildir.',
'Neredeyse her zaman bir yapıştırma sonucu sonda kalan boşluk ya da bir alanda açık diğerinde kapalı olan Caps Lock’tur. Her iki kutuyu da temizleyin ve iki kez elle yazın.',
'Zaten müşteri misiniz?',
'Zaten hesabınız var mı?',
'Zaten bir alan adınız mı var? Buraya yazın. Yoksa istediğiniz adı söyleyin, hangisinin boşta olduğunu kontrol edelim.',
'Analitik',
'Analitik ve dönüşüm takibi.',
'Duyurular bölümü',
'Destek mesajlarını yanıtlama',
'34 arasından istediğiniz 20 tanesi.',
'Diğer herhangi bir özellik veya hizmet dahil değildir',
'Sayfada görünmesini istediğiniz herhangi bir metin',
"Hâlâ eksik kalan her şey, ulaşması ne kadar sürerse teslim tarihi o kadar ötelenir. Başka hiçbir şey değişmez — fiyatınız, ödeme sayfasında kabul ettiğiniz tutarla birebir aynı kalır.",
'Sayfada yazmasını istediğiniz her şey',
'Randevu takvimi',
'Randevu hatırlatma e-postaları',
'Onaylayın, kalanı ödeyin',
'Bina için gereken her şeyi aldıktan yaklaşık 7 gün sonra. Bu, uymaya çalıştığımız bir hedeftir, koşulsuz bir garanti değildir — ve sayaç, ödemeyi yaptığınızda değil, son içeriğin ulaştığında işlemeye başlar.',
'Business Extras aylık ödeme mi?',
'Business Extras zorunlu mu?',
'Başka maliyet var mı?',
'Bunlar aylık ödeme mi?',
'Satın almadan önce sorun. Yanlış bir şey sipariş etmeniz yerine şimdi bir soruyu yanıtlamayı tercih ederiz.',
'Bunun yerine bize sorun',
'Ödeme sırasında ödeme planını onaylamanızı isteriz ve bu onayı kaydederiz. İlgili kurallar özel bir erken başlama beyanı gerektiriyorsa, o beyan aynı adıma aittir — aynı inceleme için ödeme sayfasında işaretlenmiştir.',
'Otomatik müşteri yanıtları',
'Otomatik e-posta bildirimleri',
'Geri',
'Giriş yapmaya dön',
'Fiyatlandırmaya dön',
'Başa dön düğmesi',
'Fırın',
'Berber',
'Temel SEO kurulumu',
'Temel SEO, Google dizine ekleme ve Search Console.',
"Bize hiç katılmadığınız için. Henüz var olmayan bir web sitesi için yabancıya yüzlerce euro vermek kötü bir anlaşmadır ve bunu istememeyi tercih ederiz.",
'Önce ve sonra bölümü',
'İnşaya başlamadan önce',
'Yazmaya başlamadan önce',
"Faturalandırma, web siteniz yayına girdiğinde başlar ve aşağıdaki iptal koşulları uyarınca iptal edene kadar her ay devam eder.",
'Blog bölümü',
'Rezervasyon onay e-postaları',
"Rezervasyon, SEO, analitik, otomasyon, logo ve kendi alan adınızda e-posta. Altmış altı tek seferlik iş ve on aylık hizmet; her biri kendi sayfasında fiyatlandırılır, böylece kimseyle konuşmadan seçimlerinizi işaretleyip toplama ulaşabilirsiniz.",
"Rezervasyon, SEO, analitik, otomasyon, logo ve kendi alan adınızda e-posta. Altmış altı tek seferlik iş.",
'Marka',
'Marka ve tasarım',
'Marka Kitası',
'Bozuk bağlantı kontrolü',
'Web sitenizi oluşturun ve barındırın',
'Web sitemi oluştur',
'Web sitemi oluştur —',
'Yapım güncellemeleri, yorum talepleri, ödeme hatırlatmaları, hata bildirimleri',
'Paketinizi oluşturun',
"Gerçekten yaptığınız işin çevresine kurulmuş ve telefonda çalışmak üzere tasarlanmış — çünkü insanlar sizi orada buluyor. Alan adı, barındırma ve güvenlik kilidi dahildir.",
'İş ve teknik',
'Kartvizit Tasarımı',
'İşletme Belge Şablonları',
'Business Extras',
'İşletme Bilgileri',
'İşletme adresi',
'İşletme e-postanız kurulur.',
'İşletme bilgileri',
'İşletme talep formu',
'İşletme adı',
'Web sitesi yaptığımız işletmeler',
'Kasap',
"Bir web sitesi satın almak sizi bir e-posta listesine kaydetmez. Pazarlama e-postası, ödeme sırasında ve hesap ayarlarınızda ayrı, işaretlenmemiş bir tercihtir; hayır demek satın aldığınız şeyi ya da size sağladığımız desteği etkilemez.",
'Kafe',
"Web sitemi sipariş ettikten sonra ekstra ekleyebilir miyim?",
'Sonradan aylık bir hizmet ekleyebilir veya durdurabilir miyim?',
'Aylık bir hizmeti iptal edebilir miyim?',
'Web sitesi olmadan yalnızca logo sipariş edebilir miyim?',
'Ödemeden önce bir eklentiyi çıkarabilir miyim?',
'Site yayına girdikten sonra değişiklik talep edebilir miyim?',
"Son %75'i ödemeden önce web sitesini görebilir miyim?",
'Web sitemi başka bir yere taşıyabilir miyim?',
'İptal ve İade Politikası',
'İptal ve iadeler',
'İptal etmek şurada açıklanmıştır:',
'Oto yıkama',
'Kart bilgileri, ödeme durumu, abonelikler, iadeler',
"Kart numaraları, son kullanma tarihleri ve güvenlik kodları doğrudan ödeme sağlayıcısına gider. Biz yalnızca bir referans, bir tutar ve bir durum alırız — kartın kendisini asla almayız.",
'Kariyer bölümü',
'Kataloglar ve belgeler',
'Çerez tercihimi değiştir',
'Değişiklikler',
'Değişiklikler ve bakım',
"Google, Meta veya diğer üçüncü taraf platformların yaptığı değişiklikler",
'Bu koşullardaki değişiklikler',
'Sayfadaki metni değiştirme',
'Kodunuzu kontrol edin',
'Gelen kutunuzu kontrol edin',
'Çocuklar',
'Yeni bir şifre belirleyin',
'Başlamak için bir web sitesi seçin',
'Temizle',
'Menüyü kapat',
"Kodlar ayrıca on dakika sonra kendiliğinden geçersiz olur. Yarım saat sonra bulduğunuz bir kod, doğru görünse bile reddedilir.",
'Yakında',
'İkisini karşılaştırın',
"Complete Package, Full Website artı çevresindeki işlerdir: bakım, Yerel SEO, logo ve menü tasarımı, WhatsApp Business ve işletme e-postası, ve bir yerine üç yıllık barındırma. Üçünün bedeli de tek seferde ödenir.",
'Onayla',
'Yeni şifreyi onaylayın',
'Şifreyi onaylayın',
"E-postanızı onaylayın",
'Açık rıza',
'İletişim',
"Sağlayıcının iletişim bilgileri şuradadır:",
'İletişim formu e-posta bildirimleri',
'İletişim formu spam koruması',
'İletişim bilgileri',
'Bize ulaşın',
'Sunduğunuz içerik',
]
