"""Write docs/seo-report.md from what was actually built.

    python tools/locales/report.py

Everything in the report is read back out of the generated pages, so it
describes the site as it is rather than as it was planned.
"""
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
CONFIG = json.load(open(os.path.join(HERE, 'config.json'), encoding='utf-8'))
KEYWORDS = json.load(open(os.path.join(HERE, 'keywords.json'), encoding='utf-8'))
SITE = CONFIG['site']
BUILT = [l for l in CONFIG['languages'] if l['status'] == 'built']
PLANNED = [l for l in CONFIG['languages'] if l['status'] == 'planned']
PAGES = CONFIG['pages']


def read(code, page):
    slug = page['slugs'].get('en' if page.get('english_only') else code)
    name = 'index.html' if slug == '' else slug + '.html'
    path = os.path.join(ROOT, 'en' if page.get('english_only') else code, name)
    if not os.path.exists(path):
        return None
    html = open(path, encoding='utf-8').read()

    def one(rx):
        m = re.search(rx, html, re.S)
        return m.group(1).strip() if m else ''
    return {
        'title': one(r'<title>(.*?)</title>'),
        'description': one(r'<meta name="description" content="(.*?)">'),
        'canonical': one(r'<link rel="canonical" href="(.*?)">'),
        'h1': re.sub(r'\s+', ' ', re.sub(r'<[^>]+>', ' ', one(r'<h1\b[^>]*>(.*?)</h1>'))).strip(),
        'og': one(r'<meta property="og:title" content="(.*?)">'),
        'ld': sorted(set(re.findall(r'"@type":"(\w+)"', html))),
        'hreflang': len(re.findall(r'rel="alternate" hreflang=', html)),
    }


out = ['# Xovahweb — SEO report',
       '',
       'Generated by `tools/locales/report.py` from the built pages. Rebuild with',
       '`python tools/locales/build.py`, check with `python tools/locales/audit.py`.',
       '']

out += ['## Indexable pages', '']
for page in PAGES:
    kw = KEYWORDS.get(page['key'], {})
    out.append('### %s  ·  source `%s`  ·  intent: %s'
               % (page['key'], page['source'], kw.get('intent', '—')))
    out.append('')
    codes = ['en'] if page.get('english_only') else [l['code'] for l in BUILT]
    for code in codes:
        data = read(code, page)
        if not data:
            continue
        k = kw.get(code, {})
        out += [
            '**%s**' % code,
            '',
            '- Title: %s' % data['title'],
            '- Description: %s' % data['description'],
            '- Primary keyword: %s' % k.get('primary', '—'),
            '- Secondary: %s' % (', '.join(k.get('secondary', [])) or '—'),
            '- Long-tail: %s' % (', '.join(k.get('long_tail', [])) or '—'),
            '- H1: %s' % data['h1'],
            '- Canonical: %s' % data['canonical'],
            '- Hreflang: %d alternates + x-default' % (data['hreflang'] - 1),
            '- Structured data: %s' % ', '.join(data['ld']),
            '',
        ]

out += ['## Not indexed, on purpose', '',
        '| Page | Why |',
        '| --- | --- |',
        '| /login, /signup, /trouble, /forgot-email | Sign-in screens. They answer no search and would rank above the pages that sell the work. `noindex, follow`, crawlable so the tag is seen. |',
        '| /dashboard, /admin, /onboarding, /preview | Nothing renders without a session. `noindex, nofollow` and disallowed in robots.txt. |',
        '| /emails | Internal reference for transactional email templates. |',
        '| /build | Legacy URL, redirects to the project form. |',
        '| /404 | Error page. |',
        '| The English sources in the repo root | Build inputs. Every one 301s to its /en/ URL, so there is one indexable copy of each page. |',
        '']

out += ['## Languages', '',
        'Built and published (%d): %s.' % (len(BUILT), ', '.join('%s (%s)' % (l['label'], l['code']) for l in BUILT)),
        '',
        'Prepared but not published (%d): %s.' % (len(PLANNED), ', '.join(l['code'] for l in PLANNED)),
        '',
        'A prepared language has its code, locale, writing direction and native name in',
        '`tools/locales/config.json`, but no page is published for it. Publishing English',
        'text under a foreign URL would be a duplicate, not a translation, and Google treats',
        'that as scaled content abuse. To publish one: translate the strings into',
        '`assets/i18n/<code>.js`, add its slugs and its own title and description, flip',
        '`status` to `built`, and run the build.',
        '']

open(os.path.join(ROOT, 'docs', 'seo-report.md'), 'w', encoding='utf-8', newline='') \
    .write('\n'.join(out) + '\n')
print('docs/seo-report.md')
